services:
  chatbiodescodificacion:
    build: .
    volumes:
      - ./crewai_storage:/tmp/.crewai
    container_name: chatbiodescodificacion
    restart: unless-stopped
    ports:
      - "7860:7860"
    env_file:
      - .env
    environment:
      OLLAMA_HOST: "http://192.168.1.80:11434"
      CREWAI_LLM_PROVIDER: "ollama"
      OPENAI_API_KEY:
      GRADIO_SERVER_NAME: "0.0.0.0"
      GRADIO_SERVER_PORT: "7860"
      CREWAI_STORAGE_PATH: /tmp/.crewai"
    # LÃ­mite memoria (compatible Docker viejo)
    mem_limit: 4g
